# Chezmoi configuration
# This file defines variables used in templates

[data]
    name = "Jan Mandula"
    email = "mandulaj@example.com"
    
    [data.ssh]
        nas_host = "nas"
        nas_hostname = "your-nas-ip-or-hostname"
        mint_host = "mint"
        mint_hostname = "your-mint-ip-or-hostname"
        oci_host = "oci"
        oci_hostname = "your-oci-ip-or-hostname"
        cloudflared_tunnel = "ssh.mandulaj.stream"
